#!/bin/bash

# Script to get the absolute path of the current working directory
cwd=$(cd -P -- "$(dirname -- "$0")" && pwd -P)

# Print the absolute path to terminal
echo "Current working directory: $cwd"
